name: Build conan package
on: [push, pull_request]

jobs:
  package:
    name: ${{ matrix.compiler.name }} ${{ matrix.compiler.version }} ${{ matrix.buildType }} - ${{ matrix.compiler.os }}
    runs-on: ${{ matrix.compiler.os }}
    strategy:
      matrix:
        compiler:
          - { name: "gcc", os: "ubuntu-latest", version: "10" }
          - { name: "gcc", os: "ubuntu-latest", version: "9" }
          - { name: "visual", os: "windows-latest", version: "16" }
          - { name: "visual", os: "windows-latest", version: "15" }
        buildType: ["Debug", "Release"]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Install Conan
        run: |
          pip install conan --upgrade
          pip install conan_package_tools
          conan user
      - name: Run build.py
        env:
          CONAN_BUILD_TYPES: ${{ matrix.buildType }}
        run: |
          export CONAN_${{ matrix.compiler.name }}_VERSIONS="${{ matrix.compiler.version }}"
          python build.py